name: Release

on:
  - workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [20]

    steps:
      - uses: actions/checkout@v5
      - name: Setup
        uses: ./.github/actions/setup
        with:
          node_version: ${{ matrix.node_version }}

  release:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    needs: [test]

    steps:
      - uses: actions/checkout@v5
      - name: Setup
        uses: ./.github/actions/setup

      - name: Release
        uses: ./.github/actions/release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          npm_token: ${{ secrets.NPM_TOKEN }}
